
#eureka:
#  instance:
#    instance-id: ${spring.cloud.client.ip-address}:${server.port}
#    hostname: ${spring.cloud.client.ip-address}
#    prefer-ip-address: false
#    # 超过这个时间没收到心跳就剔除这个服务，这个配置一般为服务刷新时间配置的三倍，默认90s
#    lease-expiration-duration-in-seconds: 15
#    # 服务刷新时间，默认30s
#    lease-renewal-interval-in-seconds: 5
#  client:
#    service-url:
#      default-zone: http://eurekaservice:8761/eureka/

spring:
  datasource:
    druid:
      url: jdbc:mysql://192.168.80.130:3306/file_upload_db?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
      username: root
      password: 123456
        #<!-- 配置监控统计拦截的filters -->
      filters: stat
        #<!-- 配置初始化大小、最小、最大 -->
      initial-size: 1
      min-idle: 1
      max-active: 20
        #<!-- 配置获取连接等待超时的时间 -->
      max-wait: 60000
        #<!-- 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒 -->
      time-between-eviction-runs-millis: 60000
        #<!-- 配置一个连接在池中最小生存的时间，单位是毫秒 -->
      min-evictable-idle-time-millis: 300000
      validation-query: 'select 1'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      connection-properties: 'druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000'
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        url-pattern: /druid/*
        reset-enable: false

#  redis:
#    host: 192.168.1.7
#    port: 6379
#    password: 123456
#    lettuce:
#      shutdown-timeout: 100ms
#      pool:
#        maxActive: 50
#        maxIdle: 50
#        minIdle: 10
#        maxWait: 60000
  flyway:
    enabled: true
    locations: classpath:db/migration

ftp:
  host: 192.168.80.130
  port: 21
  username: ftpadmin
  password: ftpadmin
  workDir: /
  uploadDir: /upload
  pool:
    max-total: 15
    max-idle: 10
    min-idle: 1
    test-on-borrow: true

#logging:
#  config: classpath:log4j2.xml
